### ISSUE TITLE
genesis facing token limit for usage tier 1 openai accounts - suggesting having configurable model setting

### ISSUE THREAD

**Issue by ofir-barkay** [VRSEN/agency-swarm#162]
for newly created openai accounts, the usage tier for gpt-4o is 30K TPM, which Genesis usually exceeds during new agencies creation process.
my hot fix was to switch to gpt-4o-mini by editing the model parameter in the framework's agent.py file.
I think it would be a nice addition to have the model as a configurable agency parameter (for both Genesis and all other agencies)
(+changing to mini could help one reduce testing and experimenting costs..)

**Comment by Cass0wary** [comment]
+1 would be nice if agent-swarm could catch the `Rate limit reached` error and pause for `x` number of seconds before trying again instead of terminating.

**Comment by phact** [comment]
Addressed by https://github.com/VRSEN/agency-swarm/pull/173

**Comment by desperad0s** [comment]
This is still an issue. Very discouraging for new users, after spending many hours refining my prompt and having a conversation with Genesis, and it then bouncing and failing due to rate-limit and never being able to pickup again and every time retrying, running into the same issues again.

I will try the hot fix, otherwise I might jsut try the from scratch with my prompt.
